# Defaults for flux-cloud

# clouds that are supported
clouds: [google]

# config editor
config_editor: vim

# Backend specific settings
default_cloud: google

kubernetes:
  version: '1.23'

google:
  zone: us-central1-a
  machine: n2-standard-1
  project: dinodev
