# This is intended for MiniKube, so no machine needed
matrix:
  size: [4]

  # This is only used for Google Cloud
  machine: [n1-standard-1]

# Flux Mini Cluster experiment attributes
minicluster:
  name: lammps-job
  namespace: flux-operator
  # Each of these sizes will be brought up and have commands run across it
  size: [2]

jobs:
  reaxc-hns:
    command: 'lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite'
    image: ghcr.io/rse-ops/lammps:flux-sched-focal-v0.24.0
    repeats: 5
    working_dir: /home/flux/examples/reaxff/HNS
  sleep:
    command: 'sleep 5'
    image: ghcr.io/rse-ops/lammps:flux-sched-focal-v0.24.0
    repeats: 5
    working_dir: /home/flux/examples/reaxff/HNS
  hello-world:
    command: 'echo hello world'
    image: ghcr.io/rse-ops/lammps:flux-sched-focal-v0.24.0
    repeats: 5
    working_dir: /home/flux/examples/reaxff/HNS
