name: build flux-cloud

on:
  # Always test on pull request
  pull_request: []

  # Deploy on merge to main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Container
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Make Space For Build
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc

    - name: Build and Tag Container
      run: |
        docker build -t ghcr.io/converged-computing/flux-cloud .
        set -x
        version=$(docker run -i --entrypoint flux-cloud ghcr.io/converged-computing/flux-cloud --version)
        printf "Found version ${version}\n"
        docker tag ghcr.io/converged-computing/flux-cloud:latest ghcr.io/converged-computing/flux-cloud:${version}

    - name: Login and Deploy Container
      if: (github.event_name != 'pull_request')
      run: |
        set -x
        docker images
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push --all-tags ghcr.io/converged-computing/flux-cloud
