name: test flux-cloud

on:
  pull_request: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup black linter
      run: conda create --quiet --name black pyflakes

    - name: Check Spelling
      uses: crate-ci/typos@7ad296c72fa8265059cc03d1eda562fbdfcd6df2 # v1.9.0
      with:
        files: ./docs/*/*.md ./docs/*.md ./README.md

    - name: Lint and format Python code
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate black
        pip install -r .github/dev-requirements.txt
        pre-commit run --all-files

  test-runs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ["lammps"]

    steps:
    - name: Clone the code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Install flux-cloud
      run: |
        conda create --quiet --name fc jinja2
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate fc
        pip install .[all]

    - name: Start minikube
      uses: medyagh/setup-minikube@697f2b7aaed5f70bf2a94ee21a4ec3dde7b12f92 # v0.0.9

    - name: Test ${{ matrix.test }}
      env:
        name: ${{ matrix.test }}
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate fc
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        # We need to delete the minikube cluster to bring it up again
        flux-cloud down --force-cluster --cloud minikube
        /bin/bash ./tests/test.sh ${name}
